name: "Build"
description: "Build the project"

runs:
  using: "composite"
  steps:
    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libmicrohttpd-dev

    - name: Clone prometheus client library
      shell: bash
      run: |
        git clone https://github.com/digitalocean/prometheus-client-c.git
        cd prometheus-client-c/prom
        mkdir -p build && cd build
        cmake ..
        cmake --build . -j
        sudo cmake --install .

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Cache Conan
      uses: actions/cache@v4
      with:
        path: ~/.conan2
        key: conan2-${{ runner.os }}-${{ hashFiles('conanfile.txt') }}
        restore-keys: |
          conan2-${{ runner.os }}-

    - name: Install Conan
      shell: bash
      run: |
        pip install --upgrade pip
        pip install conan
        conan --version
        conan profile detect

    - name: Conan install (Release)
      shell: bash
      run: |
        mkdir -p build
        conan install . --output-folder=build --build=missing --settings build_type=Release

    # Usamos el preset que Conan creó: "conan-release"
    - name: Configure (CMake preset)
      shell: bash
      run: cmake --preset conan-release

    - name: Build
      shell: bash
      run: cmake --build --preset conan-release -j

    # Subir el ejecutable como artefacto (ajustá la ruta si cambia)
#    - name: Upload artifact (binary)
#      if: ${{ always() }}
#      uses: actions/upload-artifact@v4
#      with:
#        name: TP1_TuxLab
#        path: build/TP1_TuxLab
